# Initial server setup
#
---
- hosts: localhost
  vars_files:
    - config.yml
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ["mas"]
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ["dock"]
    - initial-setup
    - dev
  tasks:
    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ["osx"]
    - import_tasks: tasks/dotfiles.yml
      when: configure_dotfiles
      tags: ["dotfiles"]
