---
- name: "Install homebrew packages"
  community.general.homebrew:
    name: "{{ item }}"
  state: present
  update_homebrew: yes
  with_items:
    - yabai
    - skhd

- name: Install core packages via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - karabiner-elements

- name: Start services at login
  file: src=/opt/homebrew/opt/{{ item }}/homebrew.mxcl.{{ item }}.plist path=~/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist state=link force=yes
  with_items:
    - yabai
    - skhd

- name: Setup launch agents for services
  command: launchctl load {{ home }}/Library/LaunchAgents/homebrew.mxcl.{{ item }}.plist
  with_items:
    - yabai
    - skhd

- name: Activate karabiner virtual device
  shell: xattr -dr com.apple.quarantine /Applications/.Karabiner-VirtualHIDDevice-Manager.app
  become: true

- name: Open karabiner virtual device
  shell: open /Applications/.Karabiner-VirtualHIDDevice-Manager.app
