---
- name: "Install homebrew packages"
  community.general.homebrew:
    name: "{{ item }}"
  state: present
  update_homebrew: yes
  with_items:
    - ykman
    - ykpers
    - paperkey

- name: Install core packages via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
  ignore_errors: yes
  with_items:
    - yubico-yubikey-manager
    - yubico-authenticator
    - gpg-suite-no-mail

- name: Create ~/Library/LaunchAgents
  file:
    path: ~/Library/LaunchAgents
    state: directory
    mode: "0700"

- name: Start daemon gpg at login
  copy:
    src: gpg-yubi/gpg-agent.daemon.plist
    dest: ~/Library/LaunchAgents/gpg-agent.daemon.plist
- name: Setup launch agents for services
  command: launchctl load -F {{ home }}/Library/LaunchAgents/gpg-agent.daemon.plist

- name: Set SSH environment variable for GUI
  copy:
    src: gpg-yubi/gpg-agent-symlink-ssh-auth-sock.plist
    dest: ~/Library/LaunchAgents/gpg-agent-symlink-ssh-auth-sock.plist
- name: Setup launch agents for services
  command: launchctl load -F {{ home }}/Library/LaunchAgents/gpg-agent-symlink-ssh-auth-sock.plist
